services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ~/mosquitto/config:/mosquitto/config

  influxdb:
    image: influxdb:2.7
    container_name: influx_db
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  api:
    build: ./api  # Docker va construire l'image Ã  partir de ton Dockerfile
    container_name: api_composteur
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mqtt

volumes:
  influxdb_data:
